### ISSUE TITLE
Shadow Delta Callback Status is Inconsistent with Shadow Get and Update Status

### ISSUE THREAD

**Issue by tbergeltffs** [aws/aws-iot-device-sdk-python#102]
In the response to a Shadow Get or Update the status field is set to "accepted" or "rejected" based on which MQTT topic the response came in on. This is used to indicate if the Get or Update request was accepted or rejected.

The status in the Shadow Delta callback would then be expected to be set to "delta" as that is the MQTT topic the response is coming in on. But the status is set to "delta/{ThingName}" which is inconsistent with the rest of how the API sets the status field.

This line of code appears to be the issue:
https://github.com/aws/aws-iot-device-sdk-python/blob/4b4f626fa58c36fdb9b038a4f8f8d277f30c73f0/AWSIoTPythonSDK/core/shadow/deviceShadow.py#L150

**Comment by liuszeng** [comment]
Hi @tbergeltffs ,

Thank you very much for your interest in AWS IoT Python SDK.

The issue you are pointing out is actually a historical implementation to accommodate the implementation for AWS IoT Arduino Yun SDK, since Yun SDK uses Python SDK as its back-end on the embedded Linux chip. The thing name is here to help Yun SDK to fetch the corresponding shadow callback slot. More details can be found in the following link:
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Python-Runtime/runtime/runtimeHub.py#L277

Thanks,
Liusu

**Comment by tbergeltffs** [comment]
The documentation: https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#module-AWSIoTPythonSDK.core.shadow.deviceShadow

Specifically: "responseStatus indicates whether the request has been accepted, rejected or is a delta message"

The documentation does not indicate that the "responseStatus" will have different formats for accepted, rejected and delta. If this historical implementation is going to be kept moving forward, then it would be great to have the documentation updated to reflect it.

**Comment by liuszeng** [comment]
Hi @tbergeltffs ,

Thank you for your feedback. I created an internal tracker for this. We will incorporate the documentation change in future releases.

Liusu
