### ISSUE TITLE
on_publish() callback

### ISSUE THREAD

**Issue by Venkat2811** [aws/aws-iot-device-sdk-python#11]
Hi,

on_publish() callback is not available in [mqttCore.py](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/mqttCore.py#L106) though it is available in underlying [paho client](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/paho/client.py#L477).  Why is that ?

Is there any way so that I can access underlying paho client's on_publish ?

Thanks,
Venkat

**Comment by liuszeng** [comment]
Hi @Venkat2811 ,

Thank you very much for your interest in AWS IoT Python SDK.

The current version of the AWS IoT Python SDK provides synchronous APIs built on top of the Eclipse Python Paho Client API and manages callbacks for you. Ideally you do not need to worry about triggering callbacks since it is managed and registered to Paho inside the SDK implementation.

`mqttCore.py` is a wrapper around Paho Python Client. If you really want to access the internal `on_publish` callback, you can access it through the internal Paho Python Client instance. See lines here:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/mqttCore.py#L155

As mentioned in the Paho Python MQTT Client documention, you should be able to register your own callbacks:
https://pypi.python.org/pypi/paho-mqtt/1.1#callbacks

Thanks,
Liusu

**Comment by Venkat2811** [comment]
Hi @liuszeng ,

Thank you for your clear explanation.  Yes, I was able to access through paho client instance.

Thanks,
Venkat
