### ISSUE TITLE
Problem with publish and subscribe

### ISSUE THREAD

**Issue by chuwito** [aws/aws-iot-device-sdk-python#110]
Hi,
I have a problem with publishing and subscribing to a topic from a greengrass device.
I want that my device subscribe to a topicA and when the device receives a message in topicA publish a message in topicB.
But I cannot do that in the same way. I have one script that only can subscribe and other script that only can publish. I dont know why I can do the same in one script.
My scripts are here:
Only subscribe:
https://gist.github.com/chuwito/6aeec6442c179792a8e31cfc112c5289
Only publish:
https://gist.github.com/chuwito/0470235a9864a9a1237c3b286d76dccf

Can someone help me with this?
Thanks

**Comment by liuszeng** [comment]
Hi @chuwito ,

If I understand it correctly, what you want to achieve can be described as below:
1. You have a Greengrass device (GGAD) and a Greengrass core (GGC).
2. You want your GGAD to connect to GGC and subscribe to "topicA".
3. You want your GGAD to publish a message to "topicB" whenever it receives a new message from "topicA" because of the subscription.

You can simply invoke async publish to publish to "topicB" within your message callback for "topicA" subscription. For more details you can take a look at the following sample:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/basicPubSub/basicPubSub_APICallInCallback.py#L36

Note that you will need to have the routes correctly configured and deploy your group to get the above messaging flow working. For more details, you can take a look at the Greengrass documentation:
https://docs.aws.amazon.com/greengrass/latest/developerguide/config-subs.html

Hope the above helps. Please feel free to re-open the issue or create a new thread if you have more questions.

Thanks,
Liusu
