### ISSUE TITLE
Shadow Topic QoS

### ISSUE THREAD

**Issue by tbergeltffs** [aws/aws-iot-device-sdk-python#113]
When AWS publishes to the "$aws/things/thingName/shadow/update/delta" topic which QoS level does it use to publish? I am concerned about missing messages for deltas when my client temporarily loses connection for less than the MQTT Keep Alive Timeout. If the delta message is published with QoS 1 I don't think I will lose any messages, but if it is published with QoS 0 I think I will lose the delta message.

Also, in the Python SDK in basicShadowPublish and basicShadowSubscribe the QoS is always 0. I am concerned that this will cause silent failures when doing shadow operations like shadowRegisterDeltaCallback if the client temporarily loses connection to AWS for less than the MQTT Keep Alive Timeout. Shouldn't the QoS of these shadow operations be 1? Or should there be a way for the user to control the QoS?

**Comment by liuszeng** [comment]
Hi @tbergeltffs ,

To answer your first question, the delivery effort is configured by the QoS level when you send out the subscribe request. If you request a QoS 1 subscribe to the server and that QoS level is doable from the server side, publishes to that topic will be delivered as QoS 1. However, I think the feature you are looking for is "clean session = false". In this case, server will resume the previous session and deliver pending publication deliveries. This feature is not currently supported by AWS IoT. As for now, regardless of what QoS level the server side is trying to enforce, client will not be able to receive publishes while offline. Client will always start a new session upon a successful reconnect. Any server side publishes that happen during the offline are lost.

To answer your second question, there are 2 different MQTT operations involved here:
1. Subscribe
This applies to subscribing to shadow get/update/delete accepted/rejected topics and shadow delta topic. As per MQTT spec, any subscribe request requires a SUBACK from the server. For operations like `shadowRegisterDeltaCallback`, since SDK uses synchronous API behind the scene (aka, waiting for the ack), failure in receiving SUBACK will result in either a subscribe error or timeout.
2. Publish
This applies to publishing to shadow get/update/delete topics. Currently, these publishes use QoS0 in the SDK. Provided a failed publish (QoS0, fire and forget, failed), shadow JSON document is there to make sure that we do not end up in a middle state. As long as the client gets back online, changes in shadow states will always result in delta messages and eventually make the client in sync.

Hope the above helps.

Thanks,
Liusu

**Comment by tbergeltffs** [comment]
@liuszeng Thanks for the very detailed answer. What you wrote makes sense when AWS and the client detect a disconnect. But in the case where the connection becomes unstable temporarily (without disconnecting) and a Shadow Delta Update message sent from AWS to the client may fail to be sent, will AWS try to send the Shadow Delta Update message again until it is acknowledged by the client? I would think that the client wold need to subscribe to the shadow delta topic with QoS 1 to ensure AWS ensures the client received the message.

**Comment by liuszeng** [comment]
Hi @tbergeltffs ,

Unless the client is connected and subscribed, the server will not able to deliver that delta message to that client, even if the delivery is requested as QoS 1. Being able to deliver messages arrived when the client is offline is guaranteed by "clean session = false". More details can be found in the MQTT spec (3.1.2.4):
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

A list of requirements for a "durable" client:
https://stackoverflow.com/questions/34150452/receive-offline-messages-mqtt

Thanks,
Liusu

**Comment by tbergeltffs** [comment]
@liuszeng Thanks for the quick reply. Everything you have said makes a lot of sense for the case when the client disconnects. But I am specifically asking about the case where the client does not disconnect.

Here is the scenario I am asking about:
1) client connects to AWS and gets the device shadow
2) client subscribes to device shadow delta update with QoS 0
3) client network connection degrades and some packets start being lost
4) AWS cloud changes device shadow desired state
5) AWS cloud publishes a device shadow delta update message
6) device shadow delta update message is not received by client due to lost packets
7) client network connection improves as no more packets are lost
8) client sends a ping request to AWS before the keep alive timeout triggers a disconnect
9) client and AWS are happily connected and never entered the disconnected state
10) Does AWS try again to send the device shadow delta update message to the client which was not acknowledged due to packet loss?

Because the AWS IoT Device Python SDK subscribes with QoS 0 instead of QoS 1 I am guessing that in step 10 the delta update message is not published again because it is not required to be acknowledged.

**Comment by tbergeltffs** [comment]
@liuszeng I would like to subscribe to Device Shadow Delta Updates with QoS 1 instead of the default QoS 0. I am concerned about losing shadow delta messages in a poor network environment where I may drop messages but not disconnect. Is there some underlying system in AWS that ensures shadow delta messages are always delivered and so QoS 1 is not required? Otherwise I will likely change the library locally to suit my use case.

**Comment by liuszeng** [comment]
Hi @tbergeltffs ,

Thank you very much for the clarification. Now I completely understood your concern.

Without configuring the subscription to be QoS1, you might be able to achieve this by utilizing AWS IoT Rules and an extra MQTT topic for shadow delta acks. However, I would not recommend that as it is bringing in too much complexity rather than doing a local change to enforce QoS1 subscription.

When making the changes locally, you may want to watch for synchronous subscribe/publish in shadow operations. In the implementation of shadow operations, synchronous MQTT APIs are used be default:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/shadow/shadowManager.py#L62
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/shadow/shadowManager.py#L68
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/shadow/shadowManager.py#L70
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/shadow/shadowManager.py#L71
When QoS1 is configured here, the MQTT API will block until the ACK comes back or the configured timeout happens.

In the meantime, I have added an internal tracker to make shadow operations configurable. Please let me know if you have questions moving forward.

Thanks,
Liusu

**Comment by tbergeltffs** [comment]
Allowing the QoS for Shadow Operations to be configurable in the library would be a great addition. Thanks for your help!
