### ISSUE TITLE
Disabling publishQueueDisabledException?

### ISSUE THREAD

**Issue by pickfire** [aws/aws-iot-device-sdk-python#114]
Use Cases
--------------
We disabled the AWS IoT Device SDK built-in offline publish queuing and replace it with our modified offline publish queuing to allow shutdown persistency for MQTT connections.

```python
sc = AWSIoTMQTTShadowClient(id)

mc = sc.getMQTTConnection()
mc.configureOfflinePublishQueueing(0)
```

This is how me manage connections that persists through shutdown. (not sure if it's the best way but IIRC there is some support for shutdown persistency in paho but not in aws-iot-device-sdk-python)

```python
def mqtt_cache(data):
    """Cache mqtt message."""
    if not hasattr(mqtt_cache, 'lock'):
        setattr(mqtt_cache, 'lock', threading.Lock())

    with mqtt_cache.lock:
        with open(_MQTT_CACHE, 'wb') as f:
            pickle.dump(data, f)


def mqtt_send(topic, data=None, qos=1):
    """Wrap publish with persistant across crashes.

    Args:
        topic (str): topic to publish
        data: json-serializable payload (default: :func:`_wrap_id()`)
        qos (int): quality of service (0 or 1)
    """
    m = (topic, data or _wrap_id(), 1)
    try:
        with open(_MQTT_CACHE, 'rb') as f:
            q = pickle.load(f) + [m]
    except (ValueError, IOError, EOFError):
        q = [m]
    mqtt_cache(q)

    def _publish(m):
        try:
            mc.publish(*m)  # AWSIoTMQTTClient
            q.remove(m)
            mqtt_cache(q)
            for i in q:
                logging.info('Resending %s', m)
                _publish(i)
        except Exception:
            logging.warn('Publish fail %s', m)

    threading.Thread(target=_publish, args=(m,)).start()
```

But we noticed that the exception **publishQueueDisabledException** are being thrown quite sometimes? Is there any way for us to disable that?

**Comment by liuszeng** [comment]
Hi @pickfire ,

Thank you very much for your interest in AWS IoT Python SDK.

You are right. The SDK provides an offline queue that persists requests sent while client is offline into memory. We are using this kind of strategy since it is simpler and more straightforward. Customers might have their own choice of offline message persistence strategy and could tailor the SDK to fit in their own needs.

By SDK default, `publishQueueDisabledException` is raised when the client is configured to disabled the offline queue and yet performs MQTT operations (publish/subscribe/unsubscribe) while offline. You can ignore that by simply doing a `try...except` to filter out that specific exception.

If you are modifying the SDK, a better way would be to change the underneath `OfflineRequestsManager` and `OfflineRequestQueue` so that these requests are buffered in your desired place in a desired way. More details can be found in the following links:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/workers.py#L279
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/queues.py#L26

Hope the above helps.

Thanks,
Liusu

**Comment by pickfire** [comment]
@liuszeng Thanks a lot for the quick response.

Right, I knew that `try...except` would have pretty much solved this issue. About the other method of modifying the SDK, I don't think we have any interesting in mainaining our own modified version of AWSIoTPythonSDK. I was just bumping this issue to see if there are any other alternatives other than those two.

Thanks a lot. I guess I will stick to `try...except` block.
