### ISSUE TITLE
AWS MQTT connection issue in infinite loop

### ISSUE THREAD

**Issue by amchifco** [aws/aws-iot-device-sdk-python#115]
Hello,

I am using AWS SDK to send sensors' data to the cloud
Let's consider the following code:

```
def init_aws():
    myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId)
    myAWSIoTMQTTClient.configureEndpoint(host, 8883)
    myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)

   # AWSIoTMQTTClient connection configuration
    myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
    myAWSIoTMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
    myAWSIoTMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
    myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
    myAWSIoTMQTTClient.configureMQTTOperationTimeout(5)
   
    return myAWSIoTMQTTClient`

def send(data):
    global client
    client.connect()
    client.publish(topic, data, 1)
    client.disconnect()
    time.sleep(0.1)

client = init_aws()
while True:
     send(data)
     time.sleep(1)
```

After few seconds, I obtain this error:
`ERROR:AWSIoTPythonSDK.core.mqtt_core:Connect timed out`

However, when I make an instance of init function inside the send function (so it will execute in each iteration) I never have the reported timeout problem.

Any suggestions ?

Best Regards

**Comment by liuszeng** [comment]
Hi @amchifco ,

Thank you very much for providing this information. I was able to duplicate your issue occasionally. When I checked the corresponding cloudwatch logs, I found the following:
```
2018-03-07 21:55:54.889 TRACEID:0a5dd1cf-27d8-2d54-7634-418355c35a7e PRINCIPALID:8d23e5739478cdbc42f545ebbe47f62805cd43b6ea7258a28fe3a1dbcc76336b [ERROR] EVENT:MQTT Client Connect MESSAGE:Connect Status: CLIENT_ERROR Failure reason:throttled
```

Can you check your cloudwatch log to see if similar log outputs happened?

AWS IoT has a throttling limit on the number of connect per account per client id for 1 transaction per second (TPS). You can check out the detailed description here:
https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot

I guess what happened is that, your client was getting throttled because of too frequent MQTT CONNECT attempts (TPS > 1) when you use a global client variable. When you switch to initializing the client within `send(...)`, extra lines of initialization code consumes more time and makes the interval longer. As a result, you will be less likely to get throttled.

Hope the above helps.

Thanks,
Liusu

**Comment by amchifco** [comment]
Thanks for the prompt response ! That explains the issue ..

Cheers
