### ISSUE TITLE
Getting standalone exe for aws iot sdk, openssl (python)

### ISSUE THREAD

**Issue by TejaswiniiB** [aws/aws-iot-device-sdk-python#118]
Hi, is it possible to get a standalone .exe (which includes my python code using AWS IOT SDK python too), avoiding separate installation of openssl, python, AWSIoTPythonSDK for windows?

Thankyou !!

**Comment by hedeshianaws** [comment]
Unfortunately, this is a pretty common question across Python based projects in general. As you are probably aware, Python does not generate directly executable files since it is a runtime interpreted language. While a standalone exe may not be directly possible, there several projects unaffiliated with AWS (such as PyInstaller) which let you package your Python application for distribution. You can try searching for "packaging python programs windows" (without the quotes) for further examples on how to accomplish this.

If none of these solutions will work for you, and you must have a native system binary with all dependencies statically linked, then I would recommend looking into the AWS IoT C++ Device SDK to better suite your needs.

**Comment by TejaswiniiB** [comment]
Okay , thankyou !!
