### ISSUE TITLE
publishQueueDisabledException

### ISSUE THREAD

**Issue by Venkat2811** [aws/aws-iot-device-sdk-python#13]
Hi,

Why can't I disable offlinePublishQueue ?

When I disable it I'm getting publishQueueDisabledException

Thanks,
Venkat

**Comment by liuszeng** [comment]
Hi @Venkat2811 ,

Thank you very much for using AWS IoT Python SDK!

While offline, the SDK will try to enqueue the publish requests so that these requests can be resent upon client reconnect. When the offlinePublishQueue is disabled, offline publish requests will not be queued (since queue size is configured to be 0) and the publishQueueDisabledException will be raised to indicate the loss of offline requests. If the queue is full, the publishQueueFullException will be raised to indicate the loss of offline requests that exceeds the maximum capacity of the queue. If you do not want to worry about queue size, you can either configure the offline publish queue to be infinite (queue size = -1) and the SDK will do the resend for you, or you can catch and ignore that exception.

Thanks,
Liusu

**Comment by Venkat2811** [comment]
Hi @liuszeng 

Thanks for explaining :)

Thanks,
Venkat.
