### ISSUE TITLE
Confused By Method Naming & Docs

### ISSUE THREAD

**Issue by drcoll** [aws/aws-iot-device-sdk-python#16]
It took me quite some time and digging through an already [closed issue](https://github.com/aws/aws-iot-device-sdk-python/issues/3) to figure out how to register a specific "Thing" shadow to the device shadow client (and maybe I still don't understand).

From what I do understand, I needed to put my "Thing" name here, [ThingShadowEcho.py#L149](https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/ThingShadowEcho/ThingShadowEcho.py#L149), in place of 'Bot', because the shadow name IS the "Thing" name.

I propose that the function be named something like `createShadowHandlerForThing()` instead of `createShadowHandlerWithName()`, as it more explicitly implies you are creating a handler **for** a device (thing), instead of creating, and seemingly arbitrarily naming, a handler for shadows.

That or update the docs to be a little more clear? I didn't see anywhere in the AWS console that indicated an explicit 'Shadow Name', which is why I think I got a bit confused here.

**Comment by liuszeng** [comment]
Ho @drcoll ,

Sorry for the confusion. A device is a "thing" and you can register shadow that persists its states in AWS IoT Cloud. As is included in the AWS IoT documentation:
>A thing shadow (sometimes referred to as a device shadow) is a JSON document that is used to store and retrieve current state information for a thing (device, app, and so on). The Thing Shadows service maintains a thing shadow for each thing you connect to AWS IoT.

Since AWS IoT is using MQTT protocol for message communication, the control/data interface of a shadow is through MQTT topics. To be more specific, it wil be like '$aws/things/<shadow_name>/shadow/<operation>'. So a shadow name is the identifier of the device shadow within one region of your AWS IoT account.

For Python SDK shadow APIs, you will need to specify the shadow name so that you can create a shadow handler that allows you to perform MQTT operations (publish/subscribe/unsubscribe) to the specific MQTT topics for that device shadow.

You can find the related documentations here:
http://docs.aws.amazon.com/iot/latest/developerguide/iot-thing-shadows.html
http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html

Thanks,
Liusu
