### ISSUE TITLE
AWS IOT Python Job agent freeze in connect method

### ISSUE THREAD

**Issue by Anbarasu2507** [aws/aws-iot-device-sdk-python#188]
I'm Using below AWS Job agent code to connect device with AWS for jobagent functionality.

[https://github.com/aws/aws-iot-device-sdk-python](url)

Which is working as expected most of the time. But suddenly it struck in **connect()** method some times. So after this i cannot invoke job agent from AWS. I need to restart the jobagent program in device to get connection again (i'm using this jobagent as service in rasperypi)

Only reason i suspect is, Most of the time internet connection getting interrupted while getting connection (AWSIoTMQTTThingJobsClient).**program getting freeze in jobsClient.connect()** line.

What i need to update in my code to avoid this problem. I'm using AWSIoTPythonSDK latest **version(1.4.3)**

```
while True:
   try:
    # to check internet availability before connect
    if is_connected():
        # Init AWSIoTMQTTClient
        myAWSIoTMQTTClient = None
        if useWebsocket:
            myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId, useWebsocket=True)
            myAWSIoTMQTTClient.configureEndpoint(host, port)
            myAWSIoTMQTTClient.configureCredentials(rootCAPath)
        else:
            myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId)
            myAWSIoTMQTTClient.configureEndpoint(host, port)
            myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)

        # AWSIoTMQTTClient connection configuration
        myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
        myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
        myAWSIoTMQTTClient.configureMQTTOperationTimeout(10)  # 5 sec

        jobsClient = AWSIoTMQTTThingJobsClient(clientId, thingName, QoS=1, awsIoTMQTTClient=myAWSIoTMQTTClient)

        jobsClient.connect()
        jobsMsgProc = JobsMessageProcessor(jobsClient, clientId)
        jobsMsgProc.processJobs()
        while not jobsMsgProc.isDone():
            time.sleep(2)
    else:
        print("Internet connection NA")
        time.sleep(60)
  except (connectTimeoutException,publishTimeoutException,subscribeTimeoutException):
    time.sleep(60)
    try:
        jobsClient.disconnect()
    except:
        pass
  except Exception as e:
    time.sleep(60)
    try:
        jobsClient.disconnect()
    except:
        pass
```

**Comment by Anbarasu2507** [comment]
closed

**Comment by JonathanHenson** [comment]
have your tried setting a connect timeout? myAWSIotMQTTClient.configureConnectDisconnectTimeout()

**Comment by Anbarasu2507** [comment]
Hi @JonathanHenson Thank you for your response ,
        Yes i have configured  configureConnectDisconnectTimeout() to 10 sec . 
this is my configuration,
```
myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myAWSIoTMQTTClient.configureMQTTOperationTimeout(10)  # 5 sec
```

**Comment by graebm** [comment]
I see that you've started with the `jobsSample.py` sample app, and wrapped its core functionality in a while loop. The sample app is intended to exist when there are no jobs left to run. In your program, when there are no jobs left to run (when `jobsMsgProc.isDone()` returns true), the loop repeats, another MQTT client class is created and attempts to connect. But the previous MQTT client class never disconnected, and is still being used by the previous `JobsMessagProcessor` instance, .... things are just in a weird state.

The sample app is intended to be a short and easy to read starting point. They're not terribly robust with error handling. Here's are some suggestions. I assume you want a program that executes pending jobs, but when there are no jobs left to do, does not exit, it continues waiting for any future jobs to appear.

- Don't recreate the MQTT client in a loop. The MQTT client has logic that attempts to reconnect whenever the connection is lost. So you can just keep 1 client around forever and it will reconnect itself as necessary.
- Don't exit when the `JobsMessageProcessor.isDone()` returns true, unless you modify that function to return true when you truly want it to.
- Move error-handling closer to the source of the error. Instead of wrapping the whole main loop in a single try-block, just try to catch `connectTimeoutException` from the `connect()` call, and just try to catch `subscribeTimeoutException` where subscribes are happening
