### ISSUE TITLE
Document or give better errors for SSL issues

### ISSUE THREAD

**Issue by dkarchmer** [aws/aws-iot-device-sdk-python#2]
Hi,
I am trying to do a simple publish, but the connect() function gives me

```
[12/Jul/2016 12:49:39] ERROR  [SSL] PEM lib (_ssl.c:2581)
```

My guess is this is related to not using the proper OpenSSL, but it looks good.

Running on a Mac, with Python 2.7.11, and `SSL Version OpenSSL 1.0.2h  3 May 2016`

I have another equivalent node.js script and that works, so I know the certificates and AWS is ok. Any idea?

The script is:

```
    myMQTTClient = AWSIoTMQTTClient('0000-10000000')  # Name of my Thing on AWS IoT console
    # For TLS mutual authentication
    myMQTTClient.configureEndpoint('XXXXXXXXXXXXX.iot.us-east-1.amazonaws.com', 8883)
    myMQTTClient.configureCredentials(
        './certs/root-CA.crt',
        './certs/0000-10000000-certificate.pem.crt',
        './certs/0000-10000000-private.pem.key'
    )
    myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
    myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
    myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
    myMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec

    try:
        myMQTTClient.connect()
    except Exception as e:
        logger.error(str(e))
        sys.exit(1)
```

Also, the following POHO script works

```
awshost = "XXXXXXXXXXX.iot.us-east-1.amazonaws.com"
awsport = 8883
caPath = "./certs/root-CA.crt"
certPath = "./certs/0000-10000000-certificate.pem.crt"
keyPath = "./certs/0000-10000000-private.pem.key"

mqttc.tls_set(caPath,
              certfile=certPath,
              keyfile=keyPath,
              cert_reqs=ssl.CERT_REQUIRED,
              tls_version=ssl.PROTOCOL_TLSv1_2,
              ciphers=None)

mqttc.connect(awshost, awsport, keepalive=60)
```

**Comment by liuszeng** [comment]
Hi @dkarchmer ,

Thank you very much for using AWS IoT Python SDK!

For X509 certificate based mutual authentication, a set of certificates need to be provided in order to connect to AWS IoT. In IoT Python SDK, an API is provided for certificate configuration:

    myMQTTClient.configureCredentials(CAFilePath, KeyPath='', CertificatePath='')

In the script you provided, it seems that there is a misconfiguration for client certificate file and private key file. It should be like this:

    ...
    myClient.configureCredentials('./certs/root-CA.crt', './certs/0000-10000000-private.pem.key', './certs/0000-10000000-certificate.pem.crt')
    ...

More details about API can be found here:
https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html

You can also use the provided samples as a reference:
https://github.com/aws/aws-iot-device-sdk-python/tree/master/samples

Can you try again and see if it gets connected?

Thanks,
Liusu

**Comment by dkarchmer** [comment]
Swapped the KeyPath and CertificatePath. Sorry :-)
