### ISSUE TITLE
sendJobsUpdate must be wrapped with a thread?

### ISSUE THREAD

**Issue by xyk2** [aws/aws-iot-device-sdk-python#203]
Looking at the [jobsSample script](https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/jobs/jobsSample.py) at line 59, the update request is wrapped in a thread:

```python
threading.Thread(target = self.awsIoTMQTTThingJobsClient.sendJobsUpdate, kwargs = {'jobId': execution['jobId'], 'status': jobExecutionStatus.JOB_EXECUTION_SUCCEEDED, 'statusDetails': statusDetails, 'expectedVersion': execution['versionNumber'], 'executionNumber': execution['executionNumber']}).start()
```

Is there a specific reason for this? I tried just directly calling 

```python
self.awsIoTMQTTThingJobsClient.sendJobsUpdate(myJobId, jobExecutionStatus.JOB_EXECUTION_SUCCEEDED)
```
 and it always times out with a `AWSIoTPythonSDK.exception.AWSIoTExceptions.publishTimeoutException` but in the IoT console it still registers as a successful execution.

**Comment by graebm** [comment]
The way the sample is written, yes. `sendJobsUpdate()` does need to be invoked on a thread.

`sendJobsUpdate()` performs a synchronous MQTT publish call under the hood.
Line 59 is in a callback that's being invoked by the MQTT client.
I would guess that since the callback's is calling back into the MQTT client again, the MQTT client isn't able to tick its internal logic and notice that a PUBACK has come back on the wire, so the synchronous `sendJobsUpdate()` thinks it timed out

Does that make sense?
