### ISSUE TITLE
Publish Error 4

### ISSUE THREAD

**Issue by kilabyte** [aws/aws-iot-device-sdk-python#222]
Hello,

After around 15k submissions (i publish once every 30 seconds) when the loop goes to publish i get:

`INFO:AWSIoTPythonSDK.core.protocol.mqtt_core:Performing async publish...
ERROR:AWSIoTPythonSDK.core.protocol.mqtt_core:Publish error: 4`

Now looking through the documentation; there is nothing on this. Looking through the code; i can't find anywhere that shows error 4 and what it means.

Im running on a Raspberry Pi 3 with python 3.7.3.

Any help would be appreciated.
Thanks!

**Comment by graebm** [comment]
The 4 is coming from `AWSIoTPythonSDK.core.paho.client.MQTT_ERR_NO_CONN = 4`.

The SDK's `AWSIoTMQTTClient` class wraps the 3rd party "Paho" MQTT client. These logs are reporting on some internal details of Paho, it may not be a real problem for you. Paho's publish call returns 0 (success) or 4 (offline). The SDK's wrapper class's publish call returns True or False, because that is easier to comprehend.

If you're publishing with QoS 0 there is no guarantee that the message will ever send, so if the internet connection is randomly dropped, QoS 0 messages will just fail to send and that is fine, that's what QoS 0 is for.

If you're publishing QoS 1, then failed publish messages will try to send again unless:
- the internal queue of QoS1 messages is completely full (unlikely)
- you're using the synchronous `.publish()` which times out after a fixed amount of time.

If you need your message to be delivered eventually use `publishAsync()` with QoS 1.

**Comment by kilabyte** [comment]
OK then i can just ignore this error and once internet connectivity is regained should i do another .connect() and it'll dump all the queue to publish? Yes i am currently using publishAsync() with QoS 1.

**Comment by kilabyte** [comment]
Going back to this issue im seeing the connection randomly drop fine so i put in a manual disconnect and connect to re-establish the connection but no never does. I have to full null out the client object and realloc and connect for it to work again

**Comment by graebm** [comment]
The MQTT client will automatically reconnect if the connection is lost, you should not manually call connect() again.

You also should not manually call disconnect() unless you are gracefully shutting down your application and want the server to know about it. I believe the MQTT client code takes a manual call to disconnect() to mean that the client will be going away. This is why you found the object unusable after calling disconnect().

The MQTT Client is intended to handle connections that periodically drop out. You don't need to do anything special. The client will reconnect and send QoS1 message that were published while it was offline.

**Comment by kilabyte** [comment]
This is correct i shouldn't need to issue the connection disconnection again. However if i dont do it this way it barley lasts 8 hours
