### ISSUE TITLE
MQTT publish timeout error while using multiprocessing python

### ISSUE THREAD

**Issue by SaiHaneeshAllu** [aws/aws-iot-device-sdk-python#274]
Hi. I run two python scripts one of which subscribes and publishes to the IOT. when i run the script using multiprocessing python, i always get Publish timeout error. But while running them without multiprocessing, there are no issues.

Hi. I tried to run two scripts using multiprocessing as follows:
```
import multiprocessing
from file1 import function1
from file2 import function2

files=[function1,function2]

if __name__ == "__main__":
    for name in files:
        process = multiprocessing.Process(target=name)
        process.start()
```
Any suggestions on how to resolve it

**Comment by jmklix** [comment]
I'm a little confused on how you have this set up. Are both functions publish functions or is function1 subscribe and function2 is publish?

**Comment by SaiHaneeshAllu** [comment]
function1 calls few other functions that subscribe and publish. Below is the structure

**X.py**
-->global variable
-->subscribe()  ->> updates the global variable

**Y.py**
import X
**function1()**
        |---calculations  ->>uses the global variable from X
        |---publish()
**function2()**
        |---calculations     no publish, subscribe here

**Comment by jmklix** [comment]
Sorry, but I'm still having problems replicating this and I'm not sure how you are trying to use multiprocessing with the structure in your reply. Can you provide the following info:

**Platform/OS/Device**
What are you running the sdk on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs/output**
If applicable, add logs or error output.

**Comment by SaiHaneeshAllu** [comment]
Hi @jmklix , I think I should close this issue. I have moved on from using it in multiprocessing . Thanks for your support and regret any inconveniences
