### ISSUE TITLE
Python Paho Mqtt error cannot connect to thing on AWS IoT

### ISSUE THREAD

**Issue by kejsiStruga** [aws/aws-iot-device-sdk-python#31]
I am facing problems, when trying to connect to AWS IoT via python. My code worked previously so there isn't anything I can change there, I suspect there is something on AWS side probably ? As you can see at the last line I am having SSL problems.
`Traceback (most recent call last): File "flint.py", line 44, in <module> mqttc.connect("a2yye602yte99c.iot.us-west-2.amazonaws.com", port=8883) #AWS IoT service hostname and portno File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 686, in connect return self.reconnect() File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 821, in reconnect ciphers=self._tls_ciphers) File "/usr/lib/python2.7/ssl.py", line 891, in wrap_socket ciphers=ciphers) File "/usr/lib/python2.7/ssl.py", line 566, in __init__ self.do_handshake() File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:581)`

Also yesterday when the error popped in for the first time, there was some notification on AWS IoT console :
![notify](https://cloud.githubusercontent.com/assets/20498500/22140003/1d483c52-deea-11e6-8232-9a1636c811ff.PNG)

**Comment by kejsiStruga** [comment]
@aws-dpt Please, it would be very grateful if you could reply on this issue. I fixed it by issuing new certificates for my raspberry pi thing, BUT NOW it is HAPPENING AGAIN ! I can't find an explanation on this case.

Thank you

**Comment by liuszeng** [comment]
Hi @kejsiStruga ,

Can you provide the details about:
1. Python Paho client version
2. SSL version compiled with the Python executable
3. TLS configuration of the client

Also, can you enable the cloudwatch log and see if there is any suspicious logging output when the issue happens? To enable cloudwatch log for AWS IoT, please check out this [documentation](http://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html).

In the mean time, we will reach out our internal service team to see if we can get more information about the notification you saw in your AWS IoT Console.

Thanks,
Liusu

**Comment by liuszeng** [comment]
Hi @kejsiStruga ,

We have not heard from you for a while. We are closing the issue for now. If you have more questions, please feel free to re-open this issue or start a new thread. Thank you again for your interest in AWS IoT Device SDK for Python.

Liusu

**Comment by kejsiStruga** [comment]
Hi @liuszeng , 

It's not that i have solved the issue, but the problem isn't appearing anymore. i am pretty sure it was some DNS problem.

Thank you!

**Comment by embRTS** [comment]
HI @kejsiStruga 

I am also facing the problem 
My set up 
MQTT paho client running in raspberry pi3

when i am trying to run the python script I am getting 

`pi@NotAvailable:~ $ sudo python paho_client.py 
Traceback (most recent call last):
  File "paho_client.py", line 92, in <module>
    client.connect("a3l4kgngdhi3ds.iot.us-east-1.amazonaws.com", 8883, keepalive = 60) # this is basically end point which can be seen in aws account click on settings
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 704, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 826, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 101] Network is unreachable
`

I have created alexa skill set one day back and when i am clicking on the particular "certificate" link it is being SUBMITTED for review, 
So my question about this is it hapenning because of this certification pending or it could be any other reason 
Please let me know
I have used the steps mentioned in this web site mentioned below
[https://www.hackster.io/25439/voice-controlled-smart-home-36e37e?ref=part&ref_id=17772&offset=27](url)

**Comment by kejsiStruga** [comment]
Hello @embRTS , in case your certificate is in pending mode than it is not possible to connect to AWS (SSL encryption works this way, your first have to get authenticated that you are who you are pretending to be and afterwards you exchange data) . I am guessing you cannot even **telnet AWS**. Why don't you just create another certificate, in case this is the problem ?

In my case it was some DNS issue that appeared only when I was trying to connect with AWS using WI-FI bundle. Fixed it by changing some configurations in my router. 

Best regards, 

Kejsi

**Comment by embRTS** [comment]
Hi @kejsiStruga 
I have applied for certification 
Actually it was rejected/failure from AWS 

Let's see once they approve the certification, 

Thanks

**Comment by gbassan-br** [comment]
I had the same problem with "SSLV3_ALERT_CERTIFICATE_UNKNOWN" because the certificate was not active on AWS IoT console. Once I activated it paho is working just fine
