### ISSUE TITLE
AWS/aws-iot-device-sdk-python

### ISSUE THREAD

**Issue by Jack10101010** [aws/aws-iot-device-sdk-python#36]
When trying to run a sample start script to connect a thing to AWS IoT platform I'm getting this import error:

Runing pub/sub sample application...
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py", line 18, in <module>
    from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
ImportError: No module named AWSIoTPythonSDK.MQTTLib

I've attached the start script.

Any help would be greatly appreciated.
[start.sh.zip](https://github.com/aws/aws-iot-device-sdk-python/files/811135/start.sh.zip)

**Comment by liuszeng** [comment]
Hi @Jack10101010 ,

Thank you very much for using AWS IoT Python SDK.

It seems that you are trying to automate the steps to download the SDK from Github repo and run the sample with pre-created credentials.

In this way, your application script will be importing the SDK library as a local library (the one you downloaded), instead of importing installed libraries (via `pip install AWSIoTPythonSDK`) from Python site-packages. `import` will first search the site-packages location and then the location you run the sample for dependent libraries. Unless the library folder structure looks the same from the location you run the sample, it will not be able to find the correct library files. You can check out details about `import` here:
https://www.codementor.io/sheena/python-path-virtualenv-import-for-beginners-du107r3o1

To solve the issue, you can simply do `pip install AWSIoTPythonSDK`. In this way, the SDK library is installed to Python site-packages and will always be picked up first when you include the following line in your application script:

    from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient 

Hope the above helps.

Thanks,
Liusu

**Comment by yppgeorge** [comment]
Hi 
This error seems to persist even after performing the suggested solution by@Jack10101010 

`pi@RaspThing1:~/GGThing $ pip install AWSIoTPythonSDK
Collecting AWSIoTPythonSDK
Installing collected packages: AWSIoTPythonSDK
Successfully installed AWSIoTPythonSDK-1.4.5
pi@RaspThing1:~/GGThing $ sudo ./start.sh

Running pub/sub sample application...
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py", line 18, in <module>
    from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
ImportError: No module named AWSIoTPythonSDK.MQTTLib
pi@RaspThing1:~/GGThing $
`

Could you help in resolving this issue

Thanks

**Comment by hkayan-py** [comment]
'pip3' if you are running it in python3 environment.

**Comment by jenschr** [comment]
This is still happening if you have python3 setup. Edit your start.sh to use python3 rather than python.
Got this issue on OSX where Python 2.7 exists for legacy, but pyhton3 is recommended.

**Comment by awsjlin** [comment]
Thank you, @jenschr! Your comment solved my issue. 😀

**Comment by ADPOLLEY** [comment]
I'm getting this error too. DO I need to import the MQTT module some how?

**Comment by jallwork** [comment]
None of the above worked for me, but this did:

sudo pip install AWSIoTPythonSDK

Then enter the command (copied from the start.sh)
python aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py  ... 

Then I get:
2022-05-05 13:15:25,808 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2022-05-05 13:15:25,810 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
etc..

**Comment by v-loves-avocados** [comment]
If after you install AWSIoTPythonSDK and it still says it cannot find it, try the following:
> python
> from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

as well as 

>python3
> from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

It is possible that it works for Python3 but not Python. If that's the case, go to the very bottom of the start.sh file, and change the command from "Python" to "Python3".
