### ISSUE TITLE
connectTimeoutException happened when running basicPubSub.py

### ISSUE THREAD

**Issue by hareshel** [aws/aws-iot-device-sdk-python#49]
Trying to run the sample basicPubSub.py with -r , -c ,-k , -id option. 

connection timeout exception happened. 

INFO- ConnectionType: TLSv1.2 Mutual Autentication
mqttCore -DEBUG - Disconnect result code 1
mqttCore - ERROR- connect timeout.

Let me know any pointers what could have went wrong?

**Comment by liuszeng** [comment]
Hi @hareshel ,

Thank you very much for using AWS IoT Python SDK.

From the log you provided, it seems that the SDK is having trouble in connecting to AWS IoT. Can you check the policy attached to the certificate you are using to make sure it has proper permissions to allow you to connect with certain client ids?

For a sample policy, you can check out the following documentation:
http://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html

Thanks,
Liusu

**Comment by dvs15** [comment]
Hi @hareshel,

I had the same problem with connection. Everything was paired (Cert, Policy, Thing) and have the right data. I was thinking so.

But after I create new thing, new certs and so on, I found that problem was in **default** **"Resource":** i**n policy**. 

**"Action": "iot:*"** was right, but resource was too specific. After I change it to **"*"** everything start works fine. 

Have a nice day.

**Comment by liuszeng** [comment]
Hi @hareshel ,

We haven't heard from you for a while. We are closing this issue for now. In case you have more questions, please feel free to open up another issue. This will be helpful for us to do internal auditing.

Thanks,
Liusu
