### ISSUE TITLE
Is there a limit on number of topics to be created in AWS IoT?

### ISSUE THREAD

**Issue by mvsnbharath** [aws/aws-iot-device-sdk-python#55]
Hi,
I have used AWS IoT and have tried to connect it to my printer and it works fine, I want to scale it up-to 75 million printers with 1 topic for each printer.

I wanted to know is there a limit for number of Topics to be created per account. I did not find information regarding these  in AWS IoT Service Limits documentation. 

It's mentioned that you can scale up-to billions of devices in AWS IoT, I wanted to what are the best practices for that? (Didn't find any documentation regarding this)

So, for my particular case , I would like to know ho do I start to scale from 1 device to 75 million devices.

**Comment by gkwicker** [comment]
Hi @mvsnbharath,

For a deployment of this size, there could be a couple of different limits which may come into play.  I'd recommend filing an [AWS Service Limits increase request](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) with some details about your use-case.  We'll work with you to understand your requirements and ensure that you'll have sufficient provisioned capacity.  We can also provide specific guidance based on your application for scaling up your deployment.  Thanks for using AWS IoT!

**Comment by bsdoma** [comment]
Hi,
 I do also have same kind of usecase  where I can connect from 1 million devices to AWS IOT  .How many topics do i need to create in that case or how to do scaling with 1 topic being used across all devices ?
  Could you please provide any documentation available?

**Comment by bsdoma** [comment]
can I have any update regarding my question ?

**Comment by jeanlescure** [comment]
@gkwicker Please take into account these issues are indexed by search engines, this means other developers will arrive through google trying to find either solutions or answers. With that in mind, just diverting the issue to a link that has nothing to do with the question and providing no answer wastes the time of those of us who arrive here looking for a simple answer to the general question @mvsnbharath had, which is "**is there a limit for number of Topics to be created per account?**".

Even though this issue is closed, it is indexed and people will continue arriving here. So please, even though the issue has been closed for 3 years now, help us by providing an answer and/or a link to the pertinent documentation that lists the limit we all have been looking for.

Thank you.
