### ISSUE TITLE
why initial back off time to start with should be less than the stableConnectionTime.

### ISSUE THREAD

**Issue by mvsnbharath** [aws/aws-iot-device-sdk-python#57]
As mentioned in the AWS IoT documentation, what is the specific reason initial back off time  be less than the stableConnectionTime?

```
configureAutoReconnectBackoffTime(baseReconnectQuietTimeSecond, maxReconnectQuietTimeSecond, stableConnectionTimeSecond)
#Description
Used to configure the auto-reconnect backoff timing. Should be called before connect.
Syntax
# Configure the auto-reconnect backoff to start with 1 second and use 128 seconds as a maximum back off time.
# Connection over 20 seconds is considered stable and will reset the back off time back to its base.
myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 128, 20)
Parameters
baseReconnectQuietTimeSecond - The initial back off time to start with, in seconds. Should be less than the stableConnectionTime.
maxReconnectQuietTimeSecond - The maximum back off time, in seconds.
stableConnectionTimeSecond - The number of seconds for a connection to last to be considered as stable. Back off time will be reset to base once the connection is stable.
Returns
None
```

[https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/generated/AWSIoTPythonSDK.MQTTLib.html](url)

**Comment by liuszeng** [comment]
Hi @mvsnbharath ,

Thank you very much for your interest in AWS IoT Python SDK!

The progressive back off functionality is designed to provide an exponential back off reconnect strategy to avoid unnecessary reconnect storm hitting the remote service in a poor network environment. Once the connection is stable for the configured period of time, the SDK will reset the back off time to the base quiet period.

Considering the exponential increasing of the back off time, base quiet time is usually configured at a short time period. If stable connection time is configured less than the base quiet time, it means that we are allowing reconnect with short back off even if the connection is not that "stable", which is defeating the purpose of reducing the reconnect storm caused by unstable connection/network.

Thanks,
Liusu

**Comment by mvsnbharath** [comment]
Thank you so much for your clear explanation, it makes more sense now.
