### ISSUE TITLE
AWS IoT Reliability test?

### ISSUE THREAD

**Issue by mvsnbharath** [aws/aws-iot-device-sdk-python#58]
I am doing a reliability test to evaluate my AWS IoT Client's reconnection time, once it gets disconnected from internet.
I connected my laptop with my Mobile Data (Hotspot) and I would like to turn on/off the Data.
So,my wifi status changes from:
1) Connected to
2) Connected but no internet.

I want to know is there a procedure to know this information.(WiFi connection Status).
So, I can log all the information and know the actual re-connection time my client takes.
(I am using Windows -10)

**Comment by bxpan** [comment]
Hi Mvsnbharath,

What do you mean by re-connection time? Could you be more specific? Are you trying to find out the time interval before it tries to reconnect? Or the interval between 2 reconnects? Or you tried to find out if the sdk tells your client whether wifi is connected and has interent?

Thanks.

**Comment by mvsnbharath** [comment]
The time interval before it re-connects is configurable using the SDK.
I want to more specifically see, once the internet is up ( after going down), how much time does it take to re-connect?
Since , I am scaling I wanted to know how quickly can my client connect to AWS IoT after a disturbance in connection.
I also wanted to know, Is there any possibility of seeing the lost messages, when my client was offline i.e. when there was a connection issue and the client is not connected to AWS IoT.

**Comment by liuszeng** [comment]
Hi @mvsnbharath ,

Thank you very much for your interest in AWS IoT Device SDK for Python.

There are 2 different concepts here:
1. Time between 2 adjacent client reconnect attempts.
2. Time required for the client to establish a MQTT connection to AWS IoT.

It seems that you are looking for how long it would take between the SDK client sends the CONNECT and the client receives the CONNACK back, indicating that the MQTT connection has been successfully established to AWS IoT. Can you confirm?

Assuming that the above is true, the time it would take depends on several factors:
1. Your network environment and the AWS IoT Endpoint (region) you are connecting to.
2. The efficiency that AWS IoT Device Gateway reacts to your connect request.

One thing you can do is to utilize the AWS IoT Life cycle events to get notified when your client is connected. You can capture the timestamp when client starts the reconnect process and the timestamp when your get notified for the connected event. In this way, you can get a vague idea of how long it would take. For details about AWS IoT Life cycle event, you can check the following document:
http://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html

Since this is more of a overall AWS IoT question, not simply related to SDK only. I would recommend you to post this on [AWS Forums, IoT section](https://forums.aws.amazon.com/forum.jspa?forumID=210) to get better support from our internal teams who can give more informative suggestions.

Thanks,
Liusu

**Comment by mvsnbharath** [comment]
Hi liuszeng ,

Thanks for such a detailed response.
Not just this, you give such good answers for all my queries.

Cheers mate!!
