### ISSUE TITLE
This SDK vs Boto3

### ISSUE THREAD

**Issue by hoihu** [aws/aws-iot-device-sdk-python#6]
I'm just wondering about a general issue, maybe I'm missing something obvious.

I can send mqtt publish events using boto3. What are the advantages of this SDK vs using Boto3?

From the readme I understand there are advanced options available using this SDK which may be not present in Boto3. And on the other hand I suspect this SDK cannot manage/create certificates or create things like boto3 can.

Also I'm wondering if this SDK gets some long term, active development?

**Comment by liuszeng** [comment]
Hi @hoihu ,

Thank you very much for your interest in AWS IoT Python SDK!

AWS IoT provides several protocol support to satisfy different use cases. The message broker supports MQTT/MQTT over WebSocket to publish and subscribe and HTTPS to publish. As a general AWS SDK, the AWS Python SDK (boto3) provides HTTP based APIs for AWS IoT for [control plane](http://boto3.readthedocs.io/en/latest/reference/services/iot.html?highlight=iot) and [data plane](http://boto3.readthedocs.io/en/latest/reference/services/iot-data.html?highlight=iot), where you can perform control plane actions like create a thing, create a certificate, etc. and do simple publish. Note that it does not support long live connection to perform subscribe since it is HTTP based.

The AWS IoT Device SDK for Python provides MQTT based APIs that allow you to perform MQTT publish/subscribe through a long live MQTT connection to AWS IoT. Up on top of it, the SDK provides MQTT based shadow functionality for you to interact with device shadow in AWS IoT. It focuses on the data plane (MQTT part). As part of the AWS IoT Device SDK family, it is actively developed and maintained. We also provide IoT Device SDK support for other languages/platforms:
Embedded C:
https://github.com/aws/aws-iot-device-sdk-embedded-C
Node.js:
https://github.com/aws/aws-iot-device-sdk-js
Arduino Yun:
https://github.com/aws/aws-iot-device-sdk-arduino-yun
Java:
https://github.com/aws/aws-iot-device-sdk-java

Hope that answers your question.

Thanks,
Liusu

**Comment by hoihu** [comment]
Yes it did. Thanks for the fast reply.

**Comment by hoihu** [comment]
closed #6
