### ISSUE TITLE
Subscribe Persist

### ISSUE THREAD

**Issue by jwcook23** [aws/aws-iot-device-sdk-python#61]
Is there a specific way to make a subscribe persist? When I run my code the subscribe succeeds but then the code completes. I would expect it to hang and allow me to publish messages until I forced an interrupt. I see mqtt documentation as follows, which I believe causes a subscribe to persist:
mqttc.loop_forever()

Thanks,
Jason

```
# Import
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
import sys
import logging
import time

# Configure logging
logger = logging.getLogger("AWSIoTPythonSDK.core")
logger.setLevel(logging.DEBUG)
streamHandler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
streamHandler.setFormatter(formatter)
logger.addHandler(streamHandler)

# Callback
def customCallback(client, userdata, message):
        topic = message.topic
        payload = message.payload.decode("utf-8")
        print('Topic: '+topic+' Payload: '+str(payload))

# Configuration
host = 'aaa'
rootCAPath = 'aaa'
certificatePath = 'aaa'
privateKeyPath = 'aaa'
clientId = 'basicSub'
topic = 'sdk/test/Python'

myAWSIoTMQTTClient = None
myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId)
myAWSIoTMQTTClient.configureEndpoint(host, 8883)

myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)

# Connect and Subscribe
myAWSIoTMQTTClient.connect(100)
myAWSIoTMQTTClient.subscribe(topic, 1, customCallback)
```

**Comment by liuszeng** [comment]
Hi @jwcook23 ,

Thank you very much for using AWS IoT Python SDK.

MQTT requires a long live connection to the server so that the client is able to receive "push notification" from the server. In the SDK, Paho maintains the network traffic processing in another daemon thread. As for a daemon thread, here is the explanation from Python Documentation:
>A thread can be flagged as a "daemon thread". The significance of this flag is that the entire Python program exits when only daemon threads are left. The initial value is inherited from the creating thread.

That is to say, in order to keep the long live connection open, you will have to keep your main thread running. You can simply do what we have done in our SDK samples by putting a loop at the end of your script. More details can be found below:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/basicShadow/basicShadowDeltaListener.py#L110

Hope the above helps.

Thanks,
Liusu

**Comment by jwcook23** [comment]
Thanks @liuszeng for the quick response and detailed answer.
