### ISSUE TITLE
subscriptions may be silently dropped on reconnect

### ISSUE THREAD

**Issue by btashton** [aws/aws-iot-device-sdk-python#65]
in `_handle_resubscribe`  `self._internal_async_client.subscribe(topic, qos)` is  called, but there is no mechanism for checking if the subscribe failed as there was on the initial subscribe via a return code or callback.  The subscription manager will also report that there was a subscription to this.  The result is that if the connection was unstable during reconnect, we cannot know if the subscriptions were successful or not.

**Comment by liuszeng** [comment]
Hi @btashton ,

Thank you very much for your interest in AWS IoT Python SDK.

You are right. The SDK will not guarantee a successful resubscribe with a really unstable network connection. The SDK keeps the record of subscriptions based on explicit subscribe call from the user. The record will not get removed unless the user explicitly says unsubscribe/disconnect. The SDK reacts to corresponding events (ACKs, disconnect, connect, etc.) based on the callbacks invocation from the underneath Paho. When there is a disconnect and reconnect(CONNACK, non-stable client status), the resubscribe logic will be triggered correspondingly.

In an ideal case, if the network is lost in the middle of the resubscribe process, as long as the disconnect gets captured by the underneath Paho, the client status will be reset to non-stable and the resubscribe logic will be triggered upon the reception of CONNACK. However, on a really unstable network, in a corner case where the network is dropped and back on and the resubscribe attempt gets dropped in the middle, there is not subscription exists on the cloud side. This case will be true for resubscribe, offline drained QoS1 publish, subscribe and unsubscribe.

We've added this into our backlog and will try to address this in future releases. Since the subscription list is maintained by the subscription manager, as for a work-around for now, users can choose to do subscribe on those topics separately that ensures these records.

Thanks,
Liusu

**Comment by jmklix** [comment]
Sorry, but we are no longer considering any feature requests for this sdk as it is being sunsetted. The [V2](https://github.com/aws/aws-iot-device-sdk-python-v2) sdk is accepting feature requests.
