### ISSUE TITLE
How can complete, successful comm restore be detected?

### ISSUE THREAD

**Issue by anschweitzer** [aws/aws-iot-device-sdk-python#83]
As far as I can tell: 
1) When you successfully subscribe, the sdk will remember the subscription and re-subscribe on comm restore. 
2) You can provide an onOnline callback that will be called when comm is restored. 
3) When comm is restored, onOnline is called, and then previously-successfully-subscribed topics will be re-subscribed to. Until all topics have been re-subscribed to, the sdk does not consider its connection to be 'STABLE', meaning that unless you have offline requests configured you cannot publish, subscribe etc.
4) This means that when you get the onOnline event you can't really use it. Note that my onOnline event dumps messages in a queue. I'm not doing any interesting processing in the callback itself. The meaningful response is happening in another thread. Unless I insert a sleep, the response, which involves re-getting the shadow, fails. 

How is this supposed to work? A 1 second sleep seems to work at the moment, but who knows if it will always work; we would need code to handle case where it does not work. Should we be using offline requests? Detecting comm restore so we can re-get the shadow so we can catch any changes that happened offline seems like fairly basic functionality. 

Another question: what if the re-subscribe fails? It does not appear that any callback is attached, so we would just silently lose the message. Do we have to explicitly re-subscribe, with a callback, on comm restore?

**Comment by hedeshianaws** [comment]
@anschweitzer Thanks for trying out the AWS IoT python SDK. Which version of the SDK are you using?

**Comment by anschweitzer** [comment]
Thanks. 1.2.0.

**Comment by hedeshianaws** [comment]
@anschweitzer I apologize for the delay getting back to you. I had to read through the codebase myself to see what is going on. Your analysis (points 1 - 4) is spot on.  Essentially, the SDK (auto-reconnect and auto-resubscribe) are just a big wrapper around the Paho MQTT client. When the MQTT connection is established, Paho will invoke a callback on the wrapper layer whenever the MQTT connection has been established. The wrapper layer will then internally set the state to unstable, invoke the onConnect callback, and then kick off another thread to drain the offline message queue and resubscribe. Once that thread is finished, it will set the state to stable before terminating. As you've observed, this happens in the background with no notification to the client. What's worse, there does not appear to be a way for the clients to poll for the state.

I looked to see if there is some way to poll or infer the state using any of the existing APIs. What I found wat not encouraging. The only thing I could come up with is to publish() until  it returns something other than False. Of course, this will cause the SDK to queue messages and send them out thus costing you money.

It seemed the designer of this SDK intended that offline requests be used, and would certainly work in this case. I agree this behavior is pointless since since you might as well not care when you are online and just always use offline requests.

To answer you final question, the SDK doesn't even bother to check the return code of the subscribe operation when doing the resubscribes. There is no way for you to know if it failed. (https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/workers.py#L182)

I've filed two defects in our internal tracker for the Py SDK devs to take a look at. I apologize for the issues you are seeing with the SDK.

**Comment by liuszeng** [comment]
Hi @justinffs ,

We are still working on these fixes. Please stay tuned for future releases.

Thanks,
Liusu

**Comment by jinzhang-unsw** [comment]
I have experienced some wired things happen when using mqtt service. I setup onOnline and onOffline and other exception handlers already. And the connection works well in most time. But randomly it does not receive any messages from server, which means no subscribe callbacks. This may happen for 21 mins and after that suddenly all messages come in. During this period there is no any onOffline event. Is it the internal connection dropped? My setting is AutoReconnectBackoffTime(1, 32, 20)  and synchronization mode.

**Comment by mfrey** [comment]
@liuszeng Any update on the issue? Is there any chance to fix this by ourselves, open a PR to this repository and it gets eventually into master?

**Comment by KaibaLopez** [comment]
Hi @mfrey ,
Sorry about the lack of response, going through old issues and came across this one.
Not sure if you're still facing this issue, but if that's the case:
Yes, you can definitely make a pr to fix this if you have a solution in mind and it will be added if it passes our tests and reviews.
