### ISSUE TITLE
Unable to create a successful MQTT Connection!

### ISSUE THREAD

**Issue by tkamaal** [aws/aws-iot-device-sdk-python#91]
Hello, 

**Aim:**
To send a message over MQTT connection from AWS Lambda to AWS IoT to a particular topic. 

**So Far:**
I have a AWS lambda function working in python for Smart Home Skill [Cloned Repo from Alexa Smart Home Github](https://github.com/alexa/alexa-smarthome). I'm trying to integrate aws-iot-device-sdk-python to this so I can create a MQTT connection and send a message on a particular topic. But it fails to create a MQTT connection to AWS IoT. 

**Below is a code snippet.**
```
# For certificate based connection
myMQTTClient = AWSIoTMQTTClient("arn:aws:iot:us-east-1:581006103965:thing/tutorial")
# For TLS mutual authentication
myMQTTClient.configureEndpoint("tutorial", 8883)
myMQTTClient.configureCredentials("./certs/root-CA.crt", "./certs/private.pem.key", "./certs/certificate.pem.crt")

#Try MQTT Connection
logger.info("In Discover Routine!")
myMQTTClient.connect()
logger.info("Connected")
myMQTTClient.publish("Testing", "1", 0)
myMQTTClient.subscribe("Testing", 1, customCallback)
myMQTTClient.unsubscribe("Testing")
myMQTTClient.disconnect()
```
When I try to run this code, I get the following error. 

![mqttconnecterror](https://user-images.githubusercontent.com/27974027/34175975-28d88f52-e4b3-11e7-82e1-50a088b64bd4.JPG)

Please, provide some information that would be helpful in solving my issue. Any references would be of great help.

**Comment by liuszeng** [comment]
Hi @tkamaal ,

Thank you very much for using AWS IoT Device SDK for Python.

You will need to tell the SDK which IoT endpoint it should be using by setting it in `client.configureEndpoint(<ENDPOINT>, <PORT>)`. Your account specific AWS IoT MQTT endpoint should be in the following format:
```
<RANDOM_STRING>.iot.<REGION>.amazonaws.com
```
More details can be found in the corresponding API documentation:
https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.MQTTLib.AWSIoTMQTTClient.configureEndpoint

Also, for your use case to publish to an MQTT topic in an AWS Lambda function, I would recommend you to use the AWS SDK for Python (boto3), which is HTTP request/response based. This is because device SDK for Python maintains a long live MQTT connection to AWS IoT and AWS Lambda is event based and not able to keep that connection for you. If you have no need in subscribing to a topic, a simple HTTP request that publishes messages to a topic should be enough. More details can be found in the following documentation:
http://boto3.readthedocs.io/en/latest/reference/services/iot-data.html#IoTDataPlane.Client.publish

Hope the above helps.

Thanks,
Liusu

**Comment by tkamaal** [comment]
Hello @liuszeng 

Yes, that was the mistake. It worked after changing the endpoint information. Also, I will take a look at the AWS SDK for Python (boto3) too. 

Thank you. Closing this issue.
