### ISSUE TITLE
Missing Shadow Delta Callbacks

### ISSUE THREAD

**Issue by tbergeltffs** [aws/aws-iot-device-sdk-python#94]
If a Shadow Update message for version X is received before the Shadow Delta message for version X, then the registered Shadow Delta Callback is not run. I believe the Delta callback should still be run because otherwise we are not notified there is a difference between Desired and Reported state in the Shadow. I propose that the Delta callbacks should be run when the Delta message version is greater or equal to the LastVersionInSync instead of just when they are a greater version.

Specifically this line of code should change from > to >=: https://github.com/aws/aws-iot-device-sdk-python/blob/47363e9b9bc0a4ecd5896d0f90cc685498e9b3ea/AWSIoTPythonSDK/core/shadow/deviceShadow.py#L155

**Comment by liuszeng** [comment]
Hi @tbergeltffs ,

Thank you very much for pointing this out. This issue looks similar to what is mentioned here:
https://github.com/aws/aws-iot-device-sdk-python/issues/92

Updating the desired state and listening on delta messages at the same time could result in different delta handling behavior as update accepted message and delta message could come in different sequences. If you really want to process both the update (desired state) and delta message at the same time, a work-around would be dividing them into 2 different clients operating on the same shadow. More details can be found in the following samples;
https://github.com/aws/aws-iot-device-sdk-python/tree/master/samples/basicShadow
https://github.com/aws/aws-iot-device-sdk-python/tree/master/samples/ThingShadowEcho

Since there are many corner cases in handling shadow delta versions, we will need to do a careful evaluation of the change and the possible impact it could bring to the SDK behavior while supporting common use cases. We already have an internal tracker for this and will try to prioritize it against other tasks. Please stay tuned for future releases.

Thanks,
Liusu

**Comment by tbergeltffs** [comment]
In the Java IOT SDK a delta callback is generated if a delta message is received for the same version: https://github.com/aws/aws-iot-device-sdk-java/blob/5d9830bb21d167eea995dcad38e77ad6835adc7e/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/shadow/AwsIotDeviceDeltaListener.java#L69

But in the Python IOT SDK a delta callback is not generated if a delta message is received for the same version: https://github.com/aws/aws-iot-device-sdk-python/blob/47363e9b9bc0a4ecd5896d0f90cc685498e9b3ea/AWSIoTPythonSDK/core/shadow/deviceShadow.py#L155

And in the C++ IOT SDK a delta callback is not generated if a delta message is received for the same version: https://github.com/aws/aws-iot-device-sdk-cpp/blob/bf20603154eeda78f52d69eaf9c79189f0b603ea/src/shadow/Shadow.cpp#L224

The differing behaviour in how delta callbacks work compared between Java and Python/C++ when the delta is for the same version appears to be a bug. If this isn't a bug in the Python library then the different behaviour in the Java library is a bug.

**Comment by tbergeltffs** [comment]
Also the implementation in deviceShadow.py appears to imply that if I do a Get, Update or Delete then I cannot rely on Delta Update Callbacks because those other three operations all update the internal version of the client. Is the expectation that if you want to use the Delta Update Callback mechanism that you cannot do any other operations on the same client?

**Comment by liuszeng** [comment]
Hi @tbergeltffs ,

That is not true. Performing a Get, Update or Delete with an accepted response means that the client who initiated the request is aware of the latest shadow JSON document or its changes, either through delta message or accepted response. Again, the ideal use case here is device keeps updating the reported state and attempts to be in sync (through delta) with the desired state set by application.

That being said, we do realize that it is arguable that version number handling may vary from use case to use case. Device shadow version number handling could be really tricky in this way. A more flexible way might be to give access to delta version processing to the user and allow users to decide when a delta callback should be triggered.

Again, we already have an internal tracker for improving the SDK shadow logic. I will take your comment as precious input and take it into consideration in future development.

Thanks,
Liusu
